const BOOKS=[
{id:'pride',title:'Pride and Prejudice',author:'Jane Austen',genre:'Romance',year:1813,cover:'linear-gradient(145deg,#7c2d12,#fb7185)',url:'https://www.gutenberg.org/files/1342/1342-0.txt',desc:'Elizabeth Bennet navigates wit, family expectations and a complicated attraction to the proud Mr. Darcy.'},
{id:'alice',title:"Alice's Adventures in Wonderland",author:'Lewis Carroll',genre:'Fantasy',year:1865,cover:'linear-gradient(145deg,#1e3a8a,#38bdf8)',url:'https://www.gutenberg.org/files/11/11-0.txt',desc:'Alice tumbles into a strange world where logic bends, creatures talk and every turn brings a new surprise.'},
{id:'sherlock',title:'The Adventures of Sherlock Holmes',author:'Arthur Conan Doyle',genre:'Mystery',year:1892,cover:'linear-gradient(145deg,#172554,#a16207)',url:'https://www.gutenberg.org/files/1661/1661-0.txt',desc:'Brilliant detective Sherlock Holmes and Dr. Watson solve a collection of baffling London mysteries.'},
{id:'frankenstein',title:'Frankenstein',author:'Mary Shelley',genre:'Gothic',year:1818,cover:'linear-gradient(145deg,#111827,#64748b)',url:'https://www.gutenberg.org/files/84/84-0.txt',desc:'Victor Frankenstein creates life and discovers the terrible consequences of abandoning his creation.'},
{id:'dorian',title:'The Picture of Dorian Gray',author:'Oscar Wilde',genre:'Classic',year:1890,cover:'linear-gradient(145deg,#14532d,#d4af37)',url:'https://www.gutenberg.org/files/174/174-0.txt',desc:'A beautiful young man remains outwardly unchanged while a mysterious portrait records the cost of his choices.'},
{id:'dracula',title:'Dracula',author:'Bram Stoker',genre:'Horror',year:1897,cover:'linear-gradient(145deg,#450a0a,#ef4444)',url:'https://www.gutenberg.org/files/345/345-0.txt',desc:'Jonathan Harker and his allies confront the legendary Count Dracula in Bram Stoker’s landmark gothic horror.'},
{id:'jane',title:'Jane Eyre',author:'Charlotte Brontë',genre:'Romance',year:1847,cover:'linear-gradient(145deg,#4c1d95,#f0abfc)',url:'https://www.gutenberg.org/files/1260/1260-0.txt',desc:'An orphaned girl grows into an independent woman and finds love while guarding her conscience and freedom.'},
{id:'monte',title:'The Count of Monte Cristo',author:'Alexandre Dumas',genre:'Adventure',year:1844,cover:'linear-gradient(145deg,#0f172a,#64748b)',url:'https://www.gutenberg.org/files/1184/1184-0.txt',desc:'Wrongfully imprisoned Edmond Dantès escapes, finds a fortune and sets out on an extraordinary quest for justice.'},
{id:'littlewomen',title:'Little Women',author:'Louisa May Alcott',genre:'Family',year:1868,cover:'linear-gradient(145deg,#831843,#f9a8d4)',url:'https://www.gutenberg.org/files/514/514-0.txt',desc:'The four March sisters grow up together, facing love, ambition, hardship and the joys of family.'},
{id:'metamorphosis',title:'The Metamorphosis',author:'Franz Kafka',genre:'Classic',year:1915,cover:'linear-gradient(145deg,#3f3f46,#a1a1aa)',url:'https://www.gutenberg.org/files/5200/5200-0.txt',desc:'Gregor Samsa wakes to find himself transformed, forcing his family to confront fear, duty and isolation.'},
{id:'moby',title:'Moby-Dick',author:'Herman Melville',genre:'Adventure',year:1851,cover:'linear-gradient(145deg,#164e63,#22d3ee)',url:'https://www.gutenberg.org/files/2701/2701-0.txt',desc:'Ishmael joins Captain Ahab aboard the Pequod on an obsessive voyage after the white whale Moby-Dick.'},
{id:'secretgarden',title:'The Secret Garden',author:'Frances Hodgson Burnett',genre:'Family',year:1911,cover:'linear-gradient(145deg,#166534,#86efac)',url:'https://www.gutenberg.org/files/17396/17396-8.txt',desc:'A lonely child discovers a hidden garden and, with new friends, begins transforming her life.'},
{id:'tomsawyer',title:'The Adventures of Tom Sawyer',author:'Mark Twain',genre:'Adventure',year:1876,cover:'linear-gradient(145deg,#713f12,#f59e0b)',url:'https://www.gutenberg.org/files/74/74-0.txt',desc:'Tom Sawyer turns everyday life in a Mississippi town into a series of mischievous and dangerous adventures.'},
{id:'huck',title:'Adventures of Huckleberry Finn',author:'Mark Twain',genre:'Adventure',year:1884,cover:'linear-gradient(145deg,#14532d,#60a5fa)',url:'https://www.gutenberg.org/files/76/76-0.txt',desc:'Huck Finn and Jim travel down the Mississippi while wrestling with freedom, friendship and society’s rules.'},
{id:'anne',title:'Anne of Green Gables',author:'L. M. Montgomery',genre:'Family',year:1908,cover:'linear-gradient(145deg,#166534,#fda4af)',url:'https://www.gutenberg.org/files/45/45-0.txt',desc:'Imaginative orphan Anne Shirley brings energy, mistakes and wonder to the quiet community of Avonlea.'},
{id:'oz',title:'The Wonderful Wizard of Oz',author:'L. Frank Baum',genre:'Fantasy',year:1900,cover:'linear-gradient(145deg,#075985,#facc15)',url:'https://www.gutenberg.org/files/55/55-0.txt',desc:'Dorothy is swept away to Oz and follows the Yellow Brick Road with three unforgettable companions.'},
{id:'timemachine',title:'The Time Machine',author:'H. G. Wells',genre:'Science Fiction',year:1895,cover:'linear-gradient(145deg,#312e81,#22d3ee)',url:'https://www.gutenberg.org/files/35/35-0.txt',desc:'A Victorian inventor travels far into Earth’s future and discovers a civilization unlike his own.'},
{id:'waroftheworlds',title:'The War of the Worlds',author:'H. G. Wells',genre:'Science Fiction',year:1898,cover:'linear-gradient(145deg,#3f0d12,#f97316)',url:'https://www.gutenberg.org/files/36/36-0.txt',desc:'Martians invade England in one of science fiction’s most influential stories of survival and invasion.'},
{id:'invisibleman',title:'The Invisible Man',author:'H. G. Wells',genre:'Science Fiction',year:1897,cover:'linear-gradient(145deg,#0f172a,#94a3b8)',url:'https://www.gutenberg.org/files/5230/5230-0.txt',desc:'A scientist discovers a way to become invisible, but the power quickly becomes a curse.'},
{id:'junglebook',title:'The Jungle Book',author:'Rudyard Kipling',genre:'Adventure',year:1894,cover:'linear-gradient(145deg,#14532d,#a3e635)',url:'https://www.gutenberg.org/files/236/236-0.txt',desc:'Mowgli grows up among wolves and learns the laws of the jungle from a remarkable cast of animals.'},
{id:'threemusketeers',title:'The Three Musketeers',author:'Alexandre Dumas',genre:'Adventure',year:1844,cover:'linear-gradient(145deg,#1e293b,#c084fc)',url:'https://www.gutenberg.org/files/1257/1257-0.txt',desc:'Young d’Artagnan joins Athos, Porthos and Aramis for swordplay, loyalty and political intrigue.'},
{id:'scarletletter',title:'The Scarlet Letter',author:'Nathaniel Hawthorne',genre:'Classic',year:1850,cover:'linear-gradient(145deg,#7f1d1d,#fb7185)',url:'https://www.gutenberg.org/files/25344/25344-8.txt',desc:'Hester Prynne faces judgment and shame in a Puritan community while protecting a deeply personal secret.'},
{id:'taleoftwocities',title:'A Tale of Two Cities',author:'Charles Dickens',genre:'Classic',year:1859,cover:'linear-gradient(145deg,#292524,#f59e0b)',url:'https://www.gutenberg.org/files/98/98-0.txt',desc:'Love, sacrifice and revolution collide in London and Paris during the turbulent French Revolution.'},
{id:'greatexpectations',title:'Great Expectations',author:'Charles Dickens',genre:'Classic',year:1861,cover:'linear-gradient(145deg,#164e63,#fbbf24)',url:'https://www.gutenberg.org/files/1400/1400-0.txt',desc:'Pip’s sudden rise in fortune changes his ambitions, relationships and understanding of what truly matters.'},
{id:'treasure',title:'Treasure Island',author:'Robert Louis Stevenson',genre:'Adventure',year:1883,cover:'linear-gradient(145deg,#0c4a6e,#34d399)',url:'https://www.gutenberg.org/files/120/120-0.txt',desc:'Young Jim Hawkins joins a dangerous sea voyage in search of buried pirate treasure.'},
{id:'jekyll',title:'The Strange Case of Dr. Jekyll and Mr. Hyde',author:'Robert Louis Stevenson',genre:'Gothic',year:1886,cover:'linear-gradient(145deg,#27272a,#a78bfa)',url:'https://www.gutenberg.org/files/43/43-0.txt',desc:'A London doctor’s experiment divides his identity into two opposing personalities.'},
{id:'aroundworld',title:'Around the World in Eighty Days',author:'Jules Verne',genre:'Adventure',year:1872,cover:'linear-gradient(145deg,#0f766e,#fbbf24)',url:'https://www.gutenberg.org/files/103/103-0.txt',desc:'Phileas Fogg races around the world on a wager, encountering delays, dangers and unexpected friendships.'}
];
const state={genre:'All',query:'',books:BOOKS,book:null,chapter:0,text:[],font:Number(localStorage.getItem('novella-font')||20),chapters:[],loaded:false};
const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function saved(){return JSON.parse(localStorage.getItem('novella-saved')||'[]')}function progress(id){return Number(localStorage.getItem('novella-progress-'+id)||0)}function lastRead(){return JSON.parse(localStorage.getItem('novella-last')||'null')}
function toggleSave(id){let a=saved();a=a.includes(id)?a.filter(x=>x!==id):[...a,id];localStorage.setItem('novella-saved',JSON.stringify(a));if(state.book?.id===id)$('#bookmarkBtn').textContent=saved().includes(id)?'♥':'♡';render()}
function continueBooks(){return BOOKS.filter(b=>progress(b.id)>0&&progress(b.id)<100).sort((a,b)=>progress(b.id)-progress(a.id))}
function card(b){const s=saved().includes(b.id),p=progress(b.id);return `<div class="book" onclick="showDetails('${b.id}')"><div class="cover" style="background:${b.cover}"><span>${esc(b.title)}</span></div><div class="book-info"><div class="book-title">${esc(b.title)}</div><div class="book-author">${esc(b.author)}</div><div class="book-meta">${esc(b.genre)} · ${b.year}${s?' · ♥':''}</div>${p?`<div class="mini-progress"><i style="width:${Math.min(100,p)}%"></i></div><small class="muted">${p}% read</small>`:''}</div></div>`}
function render(){const filtered=BOOKS.filter(b=>(state.genre==='All'||b.genre===state.genre)&&(!state.query||`${b.title} ${b.author} ${b.genre}`.toLowerCase().includes(state.query.toLowerCase())));let view=location.hash.slice(1)||'home';if(view==='library'){const s=new Set(saved());renderPage('library',BOOKS.filter(b=>s.has(b.id)));return}if(view==='genres'){renderPage('genres',filtered);return}renderPage('home',filtered)}
function renderPage(type,books){let genres=[...new Set(BOOKS.map(b=>b.genre))];const cont=continueBooks();const popular=BOOKS.slice(0,10);const rec=lastRead()?.id?BOOKS.filter(b=>b.genre===BOOKS.find(x=>x.id===lastRead().id)?.genre&&!cont.includes(b)).slice(0,5):[];$('#app').innerHTML=`${type==='home'?`<section class="hero"><div><div class="eyebrow">Your quiet corner of the internet</div><h1>Stories worth staying up for.</h1><p>Discover timeless novels and read them beautifully, one chapter at a time.</p><div class="search"><input id="search" value="${esc(state.query)}" placeholder="Search novels, authors or genres…"><button onclick="doSearch()">Search</button></div></div><div class="hero-art"></div></section>${cont.length?`<section class="section"><div class="section-head"><h2>Continue Reading</h2><span class="muted">Pick up where you left off</span></div><div class="grid continue-grid">${cont.slice(0,5).map(card).join('')}</div></section>`:''}${rec.length?`<section class="section"><div class="section-head"><h2>Because you read this</h2><span class="muted">More in the same genre</span></div><div class="grid continue-grid">${rec.map(card).join('')}</div></section>`:''}`:''}<section class="section"><div class="section-head"><h2>${type==='library'?'My Library':type==='genres'?'Explore genres':'Popular classics'}</h2><span class="muted">${books.length} books</span></div>${type!=='library'?`<div class="chips"><button class="chip ${state.genre==='All'?'active':''}" onclick="setGenre('All')">All</button>${genres.map(g=>`<button class="chip ${state.genre===g?'active':''}" onclick="setGenre('${esc(g)}')">${esc(g)}</button>`).join('')}</div>`:''}<div class="grid" style="margin-top:18px">${books.length?books.map(card).join(''):`<div class="empty"><h3>${type==='library'?'Your library is empty':'No books found'}</h3><p class="muted">${type==='library'?'Open a novel and tap ♡ to keep it here.':'Try another title, author or genre.'}</p></div>`}</div></section>`}
function setGenre(g){state.genre=g;location.hash='genres';render()}function doSearch(){state.query=$('#search').value.trim();location.hash='home';render()}
function showDetails(id){const b=BOOKS.find(x=>x.id===id);if(!b)return;const p=progress(id),s=saved().includes(id);const related=BOOKS.filter(x=>x.genre===b.genre&&x.id!==b.id).slice(0,4);$('#detailContent').innerHTML=`<div class="detail-hero"><div class="detail-cover" style="background:${b.cover}"><span>${esc(b.title)}</span></div><div class="detail-main"><div class="eyebrow">${esc(b.genre)} · ${b.year}</div><h2>${esc(b.title)}</h2><button class="author-link" onclick="authorBooks('${esc(b.author)}')">${esc(b.author)}</button><p>${esc(b.desc)}</p><div class="detail-actions"><button class="primary" onclick="startBook('${b.id}')">${p?'Continue reading':'Read now'}</button><button class="secondary" onclick="toggleSave('${b.id}');showDetails('${b.id}')">${s?'♥ Saved':'♡ Save'}</button></div>${p?`<div class="detail-progress"><div><span>Reading progress</span><strong>${p}%</strong></div><div class="progress-track"><i style="width:${p}%"></i></div></div>`:''}</div></div>${related.length?`<section class="related"><div class="section-head"><h3>More like this</h3></div><div class="grid related-grid">${related.map(card).join('')}</div></section>`:''}`;$('#detail').classList.remove('hidden')}
function authorBooks(author){state.query='';state.genre='All';location.hash='genres';renderPage('genres',BOOKS.filter(b=>b.author===author));$('#detail').classList.add('hidden')}
function startBook(id){$('#detail').classList.add('hidden');openBook(id)}
function openBook(id){const b=BOOKS.find(x=>x.id===id);if(!b)return;state.book=b;state.chapter=Math.max(0,progress(id)-1);state.loaded=false;$('#readerTitle').textContent=b.title;$('#readerChapter').textContent=b.author;$('#bookmarkBtn').textContent=saved().includes(id)?'♥':'♡';$('#reader').classList.remove('hidden');loadText(b)}
function buildChapters(paras){const found=[];let current=[];const heading=/^(chapter|part|book|volume)\s+[ivxlcdm\d]+\b/i;paras.forEach(p=>{if(heading.test(p)&&current.length){found.push(current);current=[p]}else current.push(p)});if(current.length)found.push(current);if(found.length>=3)return found;const size=Math.max(10,Math.ceil(paras.length/12));const chunks=[];for(let i=0;i<paras.length;i+=size)chunks.push(paras.slice(i,i+size));return chunks}
async function loadText(b){$('#readerText').innerHTML='<div class="loading"><div class="spinner"></div><p>Opening your book…</p></div>';try{const r=await fetch(b.url);if(!r.ok)throw new Error('network');const raw=await r.text();const clean=raw.replace(/\r/g,'').replace(/^[\s\S]*?\*\*\* START OF[^\n]*\n/i,'').replace(/\n\*\*\* END OF[^\n]*[\s\S]*$/i,'');state.text=clean.split(/\n\s*\n/).map(x=>x.trim()).filter(x=>x.length>35);state.chapters=buildChapters(state.text);const savedChapter=JSON.parse(localStorage.getItem('novella-last')||'null');state.chapter=savedChapter?.id===b.id?Math.min(savedChapter.chapter,state.chapters.length-1):Math.min(Math.max(0,progress(b.id)-1),state.chapters.length-1);state.loaded=true;renderChapter()}catch(e){$('#readerText').innerHTML='<div class="empty"><h3>Could not open this book</h3><p class="muted">Please check your connection and try again.</p><button class="primary" onclick="loadText(state.book)">Try again</button></div>'}}
function renderChapter(){if(!state.chapters.length)return;const chapter=state.chapters[state.chapter];$('#readerText').style.fontSize=state.font+'px';$('#readerText').innerHTML=chapter.map(esc).map(p=>`<p>${p.replace(/\n/g,'<br>')}</p>`).join('');const pct=Math.round((state.chapter+1)/state.chapters.length*100);$('#progressLabel').textContent=`${pct}% · Chapter ${state.chapter+1} of ${state.chapters.length}`;$('#prevChapter').disabled=state.chapter===0;$('#nextChapter').disabled=state.chapter===state.chapters.length-1;localStorage.setItem('novella-progress-'+state.book.id,String(pct));localStorage.setItem('novella-last',JSON.stringify({id:state.book.id,chapter:state.chapter,updated:Date.now()}));localStorage.setItem('novella-font',String(state.font));$('#bookmarkBtn').textContent=saved().includes(state.book.id)?'♥':'♡'}
function changeChapter(delta){if(!state.loaded)return;const next=state.chapter+delta;if(next<0||next>=state.chapters.length)return;state.chapter=next;renderChapter();$('#reader').scrollTo({top:0,behavior:'smooth'})}
$('#closeDetail').onclick=()=>$('#detail').classList.add('hidden');$('#detail').addEventListener('click',e=>{if(e.target.id==='detail')$('#detail').classList.add('hidden')});$('#closeReader').onclick=()=>$('#reader').classList.add('hidden');$('#prevChapter').onclick=()=>changeChapter(-1);$('#nextChapter').onclick=()=>changeChapter(1);$('#fontDown').onclick=()=>{state.font=Math.max(16,state.font-1);renderChapter()};$('#fontUp').onclick=()=>{state.font=Math.min(30,state.font+1);renderChapter()};$('#bookmarkBtn').onclick=()=>{if(state.book)toggleSave(state.book.id)};$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('novella-dark',document.body.classList.contains('dark'))};document.querySelectorAll('[data-nav]').forEach(x=>x.onclick=()=>{location.hash=x.dataset.nav;render()});window.addEventListener('hashchange',render);document.addEventListener('keydown',e=>{if($('#reader').classList.contains('hidden'))return;if(e.key==='ArrowRight')changeChapter(1);if(e.key==='ArrowLeft')changeChapter(-1);if(e.key==='Escape')$('#reader').classList.add('hidden')});if(localStorage.getItem('novella-dark')==='true')document.body.classList.add('dark');render();