const $=s=>document.querySelector(s);
const content=$('#content');
let business=JSON.parse(localStorage.getItem('nexaBusiness')||'null')||{name:'Nexa Demo Business',owner:'Emmanuel',phone:'',whatsapp:'',location:'Kenya'};
const saveBusiness=()=>localStorage.setItem('nexaBusiness',JSON.stringify(business));
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
const seed={sales:[{customer:'Maya Stores',item:'20L Water Tank',amount:850,date:'Today'}],inventory:[{item:'20L Water Tank',sku:'WT-020',stock:18,price:850,status:'In stock',category:'Tanks'},{item:'10L Water Tank',sku:'WT-010',stock:6,price:520,status:'Low stock',category:'Tanks'},{item:'Tap Kit',sku:'TK-001',stock:32,price:180,status:'In stock',category:'Accessories'},{item:'Delivery Cover',sku:'DC-004',stock:0,price:250,status:'Out',category:'Accessories'}],customers:[{name:'Maya Stores',phone:'0712 000 124',orders:12,total:'KSh 18,450'},{name:'Greenline Cafe',phone:'0721 440 310',orders:7,total:'KSh 9,820'},{name:'Kiptoo Hardware',phone:'0708 812 665',orders:4,total:'KSh 5,600'}],expenses:[{name:'Delivery fuel',category:'Operations',amount:1200,date:'Today'},{name:'Packaging',category:'Stock',amount:650,date:'Yesterday'}],invoices:[{id:'NX-1048',client:'Maya Stores',amount:'KSh 4,250',status:'Paid'},{id:'NX-1047',client:'Greenline Cafe',amount:'KSh 2,850',status:'Pending'},{id:'NX-1046',client:'Kiptoo Hardware',amount:'KSh 1,800',status:'Paid'}]};
let db=JSON.parse(localStorage.getItem('nexaDB')||'null')||seed;
if(!db.orders) db.orders=[];
let cart=[];
const save=()=>localStorage.setItem('nexaDB',JSON.stringify(db));
const cartCount=()=>cart.reduce((n,x)=>n+x.qty,0);
const cartTotal=()=>cart.reduce((n,x)=>n+(Number(x.price)||0)*x.qty,0);
const money=n=> 'KSh '+Number(n||0).toLocaleString();

function rows(data){return data.map(x=>'<tr>'+x.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')}
function tableView(title,button,heads,data){
 return '<div class="section-head"><div><h2>'+title+'</h2><div class="sub">Clean records. Clear decisions.</div></div><button class="primary" onclick="openAdd(\''+title.toLowerCase()+'\')">+ '+button+'</button></div><div class="card"><table class="table"><thead><tr>'+heads.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+ (data.length?rows(data):'<tr><td colspan="'+heads.length+'" class="empty">No records yet.</td></tr>')+'</tbody></table></div>';
}
const layouts={
overview:()=>'<div class="section-head"><div><h2>'+business.name+'</h2><div class="sub">Your business at a glance.</div></div><div><button class="primary" onclick="openAdd(\'sales\')">+ New sale</button> <button class="secondary" onclick="render(\'storefront\')">View storefront</button></div></div><div class="grid stats"><div class="card stat"><span class="label">Revenue this month</span><div class="value">KSh 284,650</div><span class="delta">↑ 12.8% vs last month</span></div><div class="card stat"><span class="label">Orders</span><div class="value">186</div><span class="delta">↑ 8.4% this month</span></div><div class="card stat"><span class="label">Customers</span><div class="value">74</div><span class="delta">↑ 11 new customers</span></div><div class="card stat"><span class="label">Expenses</span><div class="value">KSh 91,240</div><span class="delta down">↑ 3.1% this month</span></div></div><div class="grid two"><div class="card"><div class="card-head"><div><h3>Revenue pulse</h3><span class="sub">Last 7 days</span></div><span class="pill">Healthy</span></div><div class="chart">'+[52,68,46,77,62,88,96].map((h,i)=>'<div class="bar" style="height:'+h+'%"><span>'+['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i]+'</span></div>').join('')+'</div></div><div class="card"><div class="card-head"><h3>Latest activity</h3><span class="sub">Live</span></div><div class="activity">'+db.sales.concat([{customer:'Greenline Cafe',item:'Order #NX-1047',amount:2850,date:'2h ago'},{customer:'Kiptoo Hardware',item:'Invoice paid',amount:1800,date:'5h ago'}]).slice(0,4).map(x=>'<div class="activity-row"><div class="avatar">'+x.customer.split(' ').map(a=>a[0]).join('').slice(0,2)+'</div><div>'+x.customer+'<small>'+x.item+' · '+x.date+'</small></div><span class="amount">'+money(x.amount)+'</span></div>').join('')+'</div></div></div>',
sales:()=>tableView('Sales','Record a sale',['Customer','Item','Amount','Date'],db.sales.map(x=>[x.customer,x.item,money(x.amount),x.date])),
orders:()=>'<div class="section-head"><div><h2>Orders</h2><div class="sub">Orders from your online shop.</div></div><button class="primary" onclick="render(\'storefront\')">Open storefront</button></div><div class="card"><table class="table"><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th></tr></thead><tbody>'+(db.orders.length?db.orders.map(o=>'<tr><td><b>'+o.id+'</b></td><td>'+o.customer+'</td><td>'+o.items.map(x=>x.name+' × '+x.qty).join(', ')+'</td><td>'+money(o.total)+'</td><td><span class="pill '+(o.status==='New'?'warn':'')+'">'+o.status+'</span></td></tr>').join(''):'<tr><td colspan="5" class="empty">No online orders yet. Share your storefront to start receiving orders.</td></tr>')+'</tbody></table></div>',
inventory:()=>'<div class="section-head"><div><h2>Inventory</h2><div class="sub">Know what is moving before it runs out.</div></div><button class="primary" onclick="openAdd(\'inventory\')">+ Add product</button></div><div class="card"><table class="table"><thead><tr><th>Product</th><th>SKU</th><th>Stock</th><th>Price</th><th>Status</th></tr></thead><tbody>'+db.inventory.map(x=>'<tr><td><b>'+x.item+'</b></td><td>'+x.sku+'</td><td>'+x.stock+'</td><td>'+money(x.price)+'</td><td><span class="pill '+(x.status==='Out'?'red':x.status==='Low stock'?'warn':'')+'">'+x.status+'</span></td></tr>').join('')+'</tbody></table></div>',
customers:()=>'<div class="section-head"><div><h2>Customers</h2><div class="sub">Every customer, relationship and purchase in one place.</div></div><button class="primary" onclick="openAdd(\'customer\')">+ Add customer</button></div><div class="card"><table class="table"><thead><tr><th>Customer</th><th>Phone</th><th>Orders</th><th>Lifetime value</th></tr></thead><tbody>'+db.customers.map(x=>'<tr><td><b>'+x.name+'</b></td><td>'+x.phone+'</td><td>'+x.orders+'</td><td>'+x.total+'</td></tr>').join('')+'</tbody></table></div>',
expenses:()=>tableView('Expenses','Add expense',['Expense','Category','Amount','Date'],db.expenses.map(x=>[x.name,x.category,money(x.amount),x.date])),
invoices:()=>'<div class="section-head"><div><h2>Invoices</h2><div class="sub">Simple billing without the spreadsheet chaos.</div></div><button class="primary" onclick="openAdd(\'invoice\')">+ New invoice</button></div><div class="card"><table class="table"><thead><tr><th>Invoice</th><th>Client</th><th>Amount</th><th>Status</th></tr></thead><tbody>'+db.invoices.map(x=>'<tr><td><b>'+x.id+'</b></td><td>'+x.client+'</td><td>'+x.amount+'</td><td><span class="pill '+(x.status==='Pending'?'warn':'')+'">'+x.status+'</span></td></tr>').join('')+'</tbody></table></div>',
storefront:()=>'<div class="storefront-shell"><div class="storefront-top"><div><span class="store-kicker">ONLINE SHOP</span><h2>'+business.name+'</h2><p>'+business.location+' · Shop directly from this business.</p></div><div class="store-actions"><button class="secondary" onclick="copyStorefront()">Copy shop link</button><button class="primary" onclick="openCart()">Cart <span id="cartCount">'+cartCount()+'</span></button></div></div><div class="store-tools"><div class="store-search"><input id="storeSearch" oninput="filterStore()" placeholder="Search products..."/><span>⌕</span></div><div id="storeFilters" class="store-filters">'+storeCategories()+'</div></div><div id="storeProducts" class="grid product-grid">'+db.inventory.map((x,i)=>productCard(x,i)).join('')+'</div><div class="store-footer"><div><b>'+business.name+'</b><span>'+business.location+'</span></div><div><span>'+(business.phone||'Phone not added')+'</span><button class="wa-link" onclick="contactBusiness()">WhatsApp enquiry →</button></div></div></div>',
settings:()=>'<div class="section-head"><div><h2>Business settings</h2><div class="sub">Make Nexa yours.</div></div></div><div class="card form-card"><div class="field"><label>BUSINESS NAME</label><input id="bizName" value="'+business.name+'"></div><div class="field"><label>OWNER / CONTACT PERSON</label><input id="owner" value="'+business.owner+'"></div><div class="field"><label>PHONE</label><input id="phone" value="'+business.phone+'" placeholder="07xx xxx xxx"></div><div class="field"><label>WHATSAPP NUMBER</label><input id="whatsapp" value="'+(business.whatsapp||business.phone||'')+'" placeholder="2547xxxxxxxx"></div><div class="field"><label>LOCATION</label><input id="location" value="'+business.location+'" placeholder="Town / County"></div><button class="primary" onclick="saveSettings()">Save changes</button></div>',};
function productCard(x,i){return '<article class="card product" data-product="'+x.item.toLowerCase()+'" data-category="'+(x.category||'Other')+'"><div class="product-icon">'+(x.image?'<img src="'+x.image+'" alt="'+x.item+'">':['◈','◇','▣','◆'][i%4])+'</div><div class="product-meta"><span class="stock-dot '+(x.stock?'':'off')+'"></span>'+(x.stock?'Available now':'Currently unavailable')+'</div><h3>'+x.item+'</h3><p>SKU '+x.sku+' · '+(x.stock?'Ready to order':'Out of stock')+'</p><div class="product-bottom"><span class="price">'+money(x.price)+'</span><button class="wa-mini" '+(x.stock?'onclick="addToCart('+i+')"':'disabled')+'>'+(x.stock?'Add to cart':'Sold out')+'</button></div></article>'}
function addToCart(index){const item=db.inventory[index];if(!item||!item.stock)return toast('This product is out of stock');const found=cart.find(x=>x.index===index);if(found){if(found.qty<item.stock)found.qty++;else return toast('Maximum available stock reached')}else cart.push({index,name:item.item,price:Number(item.price)||0,qty:1,stock:item.stock});updateCartBadge();toast(item.item+' added to cart')}
function updateCartBadge(){const el=$('#cartCount');if(el)el.textContent=cartCount()}
function openCart(){const existing=$('#cartModal');if(existing)existing.remove();const rowsHtml=cart.length?cart.map((x,i)=>'<div class="cart-row"><div><b>'+x.name+'</b><small>'+money(x.price)+' each</small></div><div class="qty"><button onclick="changeQty('+i+',-1)">−</button><b>'+x.qty+'</b><button onclick="changeQty('+i+',1)">+</button></div><strong>'+money(x.price*x.qty)+'</strong></div>').join(''):'<div class="cart-empty">Your cart is empty.<br><small>Add products from the shop to begin.</small></div>';document.body.insertAdjacentHTML('beforeend','<div class="modal-backdrop" id="cartModal" onclick="if(event.target===this)closeCart()"><div class="cart-modal"><div class="cart-head"><div><span class="store-kicker">YOUR ORDER</span><h2>Shopping cart</h2></div><button class="close-btn" onclick="closeCart()">×</button></div><div class="cart-list">'+rowsHtml+'</div>'+(cart.length?'<div class="cart-total"><span>Total</span><b>'+money(cartTotal())+'</b></div><div class="checkout-fields"><input id="orderName" placeholder="Your name"><input id="orderPhone" placeholder="Phone number"><textarea id="orderNote" placeholder="Delivery location or order note"></textarea></div><button class="primary checkout-btn" onclick="checkoutWhatsApp()">Place order on WhatsApp</button>':'')+'</div></div>')}
function closeCart(){const m=$('#cartModal');if(m)m.remove()}
function changeQty(i,delta){const x=cart[i];if(!x)return;x.qty+=delta;if(x.qty<=0)cart.splice(i,1);else if(x.qty>x.stock)x.qty=x.stock;openCart();updateCartBadge()}
function checkoutWhatsApp(){const name=$('#orderName')?.value.trim()||'Customer';const phone=$('#orderPhone')?.value.trim()||'';const note=$('#orderNote')?.value.trim()||'';if(!cart.length)return;const id='NX-'+Date.now().toString().slice(-6);const order={id,customer:name,phone,items:cart.map(x=>({name:x.name,qty:x.qty,price:x.price})),total:cartTotal(),status:'New',date:new Date().toLocaleString()};db.orders.unshift(order);save();const n=waNumber();const lines=order.items.map(x=>'• '+x.name+' × '+x.qty+' — '+money(x.price*x.qty)).join('\\n');const msg='Hello '+business.name+', I would like to place order '+id+'.\\n\\n'+lines+'\\n\\nTotal: '+money(order.total)+'\\nName: '+name+(phone?'\\nPhone: '+phone:'')+(note?'\\nNote: '+note:'');if(n)window.open('https://wa.me/'+(n.startsWith('254')?n:'254'+n.replace(/^0/,''))+'?text='+encodeURIComponent(msg),'_blank');cart=[];closeCart();updateCartBadge();toast('Order '+id+' created');setTimeout(()=>render('storefront'),350)}
function waNumber(){return String(business.whatsapp||business.phone||'').replace(/\D/g,'')}
function contactBusiness(){const n=waNumber();if(n){window.open('https://wa.me/'+(n.startsWith('254')?n:'254'+n.replace(/^0/,''))+'?text='+encodeURIComponent('Hi '+business.name+', I would like to make an enquiry.'),'_blank')}else toast('Add a WhatsApp number in Settings first')}
function enquireProduct(item,price){const n=waNumber();const name=decodeURIComponent(item);if(n){window.open('https://wa.me/'+(n.startsWith('254')?n:'254'+n.replace(/^0/,''))+'?text='+encodeURIComponent('Hi '+business.name+', I am interested in '+name+' priced at '+money(price)+'. Is it available?'),'_blank')}else toast('Add a WhatsApp number in Settings first')}
function storeCategories(){const cats=['All',...new Set(db.inventory.map(x=>x.category||'Other'))];return cats.map((c,i)=>'<button class="filter-chip '+(i===0?'active':'')+'" data-cat="'+c+'" onclick="filterCategory(this,\''+c+'\')">'+c+'</button>').join('')}
function filterStore(){const q=($('#storeSearch')?.value||'').toLowerCase();const active=document.querySelector('.filter-chip.active')?.dataset.cat||'All';document.querySelectorAll('#storeProducts .product').forEach(p=>p.style.display=(p.dataset.product.includes(q)&&(active==='All'||p.dataset.category===active))?'block':'none')}
function filterCategory(btn,cat){document.querySelectorAll('.filter-chip').forEach(x=>x.classList.remove('active'));btn.classList.add('active');btn.dataset.cat=cat;filterStore()}
function copyStorefront(){navigator.clipboard?.writeText(location.href+'#storefront').then(()=>toast('Storefront link copied')).catch(()=>toast('Copy the page address and add #storefront'))}

function saveSettings(){business={name:$('#bizName').value||'My Business',owner:$('#owner').value||'Owner',phone:$('#phone').value||'',whatsapp:$('#whatsapp').value||$('#phone').value||'',location:$('#location').value||'Kenya'};saveBusiness();toast('Business profile updated');setTimeout(()=>render('overview'),350)}
function openAdd(type){
 let html='';
 if(type==='customer')html='<div class="field"><label>NAME</label><input id="f1" placeholder="Customer name"></div><div class="field"><label>PHONE</label><input id="f2" placeholder="07xx xxx xxx"></div>';
 else if(type==='inventory')html='<div class="field"><label>PRODUCT</label><input id="f1" placeholder="Product name"></div><div class="field"><label>CATEGORY</label><input id="f4" placeholder="e.g. Tanks, Services, Accessories"></div><div class="field"><label>PRICE</label><input id="f2" type="number" placeholder="0"></div><div class="field"><label>STOCK</label><input id="f3" type="number" placeholder="0"></div><div class="field"><label>PRODUCT IMAGE URL</label><input id="f5" placeholder="https://..."></div>'
 else if(type==='invoice')html='<div class="field"><label>CLIENT</label><input id="f1" placeholder="Client name"></div><div class="field"><label>AMOUNT</label><input id="f2" type="number" placeholder="0"></div>';
 else html='<div class="field"><label>CUSTOMER</label><input id="f1" placeholder="Customer"></div><div class="field"><label>ITEM</label><input id="f2" placeholder="Product/service"></div><div class="field"><label>AMOUNT</label><input id="f3" type="number" placeholder="0"></div>';
 content.innerHTML='<div class="section-head"><div><h2>Add '+type+'</h2><div class="sub">Create a new business record.</div></div></div><div class="card form-card">'+html+'<button class="primary" id="saveBtn">Save record</button> <button class="secondary" onclick="render(\'overview\')">Cancel</button></div>';
 $('#saveBtn').onclick=()=>{const a=$('#f1')?.value,b=$('#f2')?.value,c=$('#f3')?.value;if(!a){toast('Please fill in the required field');return}if(type==='customer')db.customers.push({name:a,phone:b,orders:0,total:'KSh 0'});else if(type==='inventory')db.inventory.push({item:a,sku:'NX-'+Math.floor(Math.random()*900+100),stock:+c||0,price:+b||0,status:(+c||0)>5?'In stock':(+c||0)>0?'Low stock':'Out',category:$('#f4')?.value||'Other',image:$('#f5')?.value||''});else if(type==='invoice')db.invoices.push({id:'NX-'+Math.floor(Math.random()*9000+1000),client:a,amount:money(+b||0),status:'Pending'});else db.sales.push({customer:a,item:b,amount:+c||0,date:'Just now'});save();toast('Saved successfully');setTimeout(()=>render(type==='customer'?'customers':type==='inventory'?'inventory':type==='invoice'?'invoices':'sales'),350)}
}
function render(view){view=view||'overview';document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));const names={overview:['COMMAND CENTER','Good evening, '+(business.owner||'there')+'.'],sales:['REVENUE','Sales'],orders:['COMMERCE','Orders'],inventory:['OPERATIONS','Inventory'],customers:['RELATIONSHIPS','Customers'],expenses:['CASH FLOW','Expenses'],invoices:['BILLING','Invoices'],storefront:['GROWTH','Storefront'],settings:['SETTINGS','Business settings']};$('#eyebrow').textContent=names[view][0];$('#pageTitle').textContent=names[view][1];content.innerHTML=layouts[view]()}
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>render(n.dataset.view));$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');toast('Appearance toggled')};render(location.hash==='#storefront'?'storefront':'overview');