const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)};
let mode='photo', photoImg=null, photoState={brightness:100,contrast:100,saturation:100,blur:0,filter:'none',mood:'none',text:'',rotation:0,flip:false,sticker:'none'}, history=[],future=[],drawHistory=[];
const canvas=$('#photoCanvas'),ctx=canvas.getContext('2d');
function showMode(m){mode=m;$('.mode.active')?.classList.remove('active');$('[data-mode="'+m+'"]').classList.add('active');$('#photoWorkspace').classList.toggle('hidden',m!=='photo');$('#videoWorkspace').classList.toggle('hidden',m!=='video')}
$$('.mode').forEach(b=>b.onclick=()=>showMode(b.dataset.mode));
$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');toast('Appearance changed')};
function snapshot(){if(!photoImg)return;history.push(JSON.stringify(photoState));if(history.length>25)history.shift();future=[]}
function renderPhoto(){if(!photoImg)return;canvas.width=photoImg.naturalWidth;canvas.height=photoImg.naturalHeight;ctx.save();ctx.filter='brightness('+photoState.brightness+'%) contrast('+photoState.contrast+'%) saturate('+photoState.saturation+'%) blur('+photoState.blur+'px) '+photoState.filter;ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(photoState.rotation*Math.PI/180);ctx.scale(photoState.flip?-1:1,1);ctx.drawImage(photoImg,-photoImg.naturalWidth/2,-photoImg.naturalHeight/2);ctx.restore();if(photoState.mood!=='none'){ctx.save();ctx.globalCompositeOperation='multiply';ctx.fillStyle=photoState.mood==='warm'?'rgba(255,160,80,.16)':photoState.mood==='cool'?'rgba(70,130,255,.15)':'rgba(110,70,160,.14)';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.restore()}if(photoState.sticker!=='none'){ctx.save();ctx.font=Math.max(34,canvas.width*.07)+'px sans-serif';ctx.textAlign='center';ctx.fillText(photoState.sticker,canvas.width/2,canvas.height*.82);ctx.restore()}if(photoState.text){ctx.save();ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font=Math.max(24,canvas.width*.045)+'px Space Grotesk, sans-serif';ctx.shadowColor='#000';ctx.shadowBlur=12;ctx.fillText(photoState.text,canvas.width/2,canvas.height*.12);ctx.restore()}canvas.style.display='block';$('#photoDrop').style.display='none'}
function loadPhoto(file){if(!file?.type.startsWith('image/'))return toast('Choose an image file');const url=URL.createObjectURL(file);const im=new Image();im.onload=()=>{photoImg=im;photoState={brightness:100,contrast:100,saturation:100,blur:0,filter:'none',mood:'none',text:'',rotation:0,flip:false,sticker:'none'};history=[];future=[];renderPhoto();toast('Photo loaded')};im.src=url}
$('#choosePhoto').onclick=$('#photoUploadBtn').onclick=()=>$('#photoInput').click();$('#photoInput').onchange=e=>loadPhoto(e.target.files[0]);
$('#canvasWrap').ondragover=e=>{e.preventDefault()};$('#canvasWrap').ondrop=e=>{e.preventDefault();loadPhoto(e.dataTransfer.files[0])};
const tools={adjust:()=>'<div class="control"><label>Brightness <output id="brightOut">100</output></label><input id="brightness" type="range" min="40" max="180" value="'+photoState.brightness+'"></div><div class="control"><label>Contrast <output id="contrastOut">100</output></label><input id="contrast" type="range" min="40" max="180" value="'+photoState.contrast+'"></div><div class="control"><label>Saturation <output id="satOut">100</output></label><input id="saturation" type="range" min="0" max="200" value="'+photoState.saturation+'"></div><div class="control"><label>Soft blur <output id="blurOut">0</output></label><input id="blur" type="range" min="0" max="8" step=".5" value="'+photoState.blur+'"></div>',
filter:()=>'<p class="hint">Give your image a different character with one tap.</p><div class="filter-grid">'+[['none','Original'],['grayscale(1)','B&W'],['sepia(1)','Vintage'],['contrast(1.25) saturate(.75)','Cinematic'],['saturate(1.8)','Pop'],['hue-rotate(25deg) saturate(1.4)','Dream']].map(x=>'<button class="choice '+(photoState.filter===x[0]?'active':'')+'" data-filter="'+x[0]+'">'+x[1]+'</button>').join('')+'</div>',
text:()=>'<div class="control"><label>Headline</label><input class="text-input" id="overlayText" maxlength="36" placeholder="Type something..." value="'+photoState.text.replace(/"/g,'&quot;')+'"></div><p class="hint">Your text appears as a clean editorial overlay. Use it for stories, posters and mood cards.</p>',
draw:()=>'<button class="choice" id="rotateLeft">↺ Rotate</button> <button class="choice" id="rotateRight">↻ Rotate</button><button class="choice" id="flipPhoto">⇋ Flip</button><p class="hint">Drawing mode turns the canvas into your sketchbook. Choose a color and draw directly on the image.</p><div class="control"><label>Brush size <output id="brushOut">8</output></label><input id="brush" type="range" min="2" max="35" value="8"></div><button class="choice" id="drawToggle">Start drawing</button>',
mood:()=>'<p class="hint">Mood is a subtle color treatment designed for stories.</p><div class="filter-grid"><button class="choice" data-sticker="✨">✨ Spark</button><button class="choice" data-sticker="❤️">❤️ Love</button><button class="choice" data-sticker="☀️">☀️ Sunny</button><button class="choice" data-sticker="👀">👀 Eyes</button></div><div class="mood-grid">'+[['none','Clean'],['warm','Golden'],['cool','Midnight'],['dream','Dream']].map(x=>'<button class="choice '+(photoState.mood===x[0]?'active':'')+'" data-mood="'+x[0]+'">'+x[1]+'</button>').join('')+'</div>',
remix:()=>'<p class="hint">Remix gives your photo an instant creative direction.</p><div class="filter-grid"><button class="choice" data-remix="magazine">Magazine</button><button class="choice" data-remix="poster">Poster</button><button class="choice" data-remix="noir">Noir</button><button class="choice" data-remix="neon">Neon</button></div>'};
function panelTool(name){const title=name[0].toUpperCase()+name.slice(1);$('#toolTitle').textContent=title;$('#toolContent').innerHTML=tools[name]();bindTool(name)}
function bindTool(name){if(name==='adjust'){$$('#toolContent input').forEach(i=>i.oninput=()=>{snapshot();photoState.brightness=+$('#brightness').value;photoState.contrast=+$('#contrast').value;photoState.saturation=+$('#saturation').value;photoState.blur=+$('#blur').value;$('#brightOut').textContent=photoState.brightness;$('#contrastOut').textContent=photoState.contrast;$('#satOut').textContent=photoState.saturation;$('#blurOut').textContent=photoState.blur;renderPhoto()})}
if(name==='filter')$$('[data-filter]').forEach(b=>b.onclick=()=>{snapshot();photoState.filter=b.dataset.filter;panelTool('filter');renderPhoto()});
if(name==='text')$('#overlayText').oninput=e=>{photoState.text=e.target.value;renderPhoto()};
if(name==='mood'){$('[data-sticker]').forEach(b=>b.onclick=()=>{photoState.sticker=b.dataset.sticker;renderPhoto()});}if(name==='mood')$('[data-mood]').forEach(b=>b.onclick=()=>{snapshot();photoState.mood=b.dataset.mood;panelTool('mood');renderPhoto()});
if(name==='remix')$$('[data-remix]').forEach(b=>b.onclick=()=>{snapshot();const r=b.dataset.remix;if(r==='magazine'){photoState.filter='contrast(1.12) saturate(.8)';photoState.text='THE MOMENT'}if(r==='poster'){photoState.filter='contrast(1.3) saturate(1.5)';photoState.text='MAKE IT MATTER'}if(r==='noir'){photoState.filter='grayscale(1) contrast(1.35)';photoState.text='AFTER DARK'}if(r==='neon'){photoState.filter='saturate(2) hue-rotate(35deg)';photoState.text='NIGHT ENERGY'}renderPhoto();toast('Remix applied')});
if(name==='draw'){if($('#drawToggle'))$('#drawToggle').onclick=()=>startDrawing(+$('#brush').value);$('#rotateLeft').onclick=()=>{snapshot();photoState.rotation=(photoState.rotation+270)%360;renderPhoto()};$('#rotateRight').onclick=()=>{snapshot();photoState.rotation=(photoState.rotation+90)%360;renderPhoto()};$('#flipPhoto').onclick=()=>{snapshot();photoState.flip=!photoState.flip;renderPhoto()}}}
$$('.tool').filter(b=>b.dataset.tool).forEach(b=>b.onclick=()=>{$$('.tool').filter(x=>x.dataset.tool).forEach(x=>x.classList.remove('active'));b.classList.add('active');panelTool(b.dataset.tool)});
$('#undoBtn').onclick=()=>{if(!history.length)return toast('Nothing to undo');future.push(JSON.stringify(photoState));photoState=JSON.parse(history.pop());renderPhoto()};
$('#redoBtn').onclick=()=>{if(!future.length)return toast('Nothing to redo');history.push(JSON.stringify(photoState));photoState=JSON.parse(future.pop());renderPhoto()};
$('#resetBtn').onclick=()=>{if(!photoImg)return;photoState={brightness:100,contrast:100,saturation:100,blur:0,filter:'none',mood:'none',text:'',rotation:0,flip:false,sticker:'none'};history=[];future=[];renderPhoto();toast('Photo reset')};
$('#downloadPhoto').onclick=()=>{if(!photoImg)return toast('Add a photo first');const a=document.createElement('a');a.download='nexa-studio-'+Date.now()+'.png';a.href=canvas.toDataURL('image/png');a.click();toast('Photo exported')};
function startDrawing(size){if(!photoImg)return toast('Add a photo first');let drawing=false;canvas.onpointerdown=e=>{drawing=true;ctx.beginPath();const p=point(e);ctx.moveTo(p.x,p.y)};canvas.onpointermove=e=>{if(!drawing)return;const p=point(e);ctx.lineTo(p.x,p.y);ctx.strokeStyle='#b8ff55';ctx.lineWidth=size;ctx.lineCap='round';ctx.stroke()};canvas.onpointerup=()=>drawing=false;toast('Draw directly on your photo')};function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
panelTool('adjust');

let videoUrl='',videoReady=false;const video=$('#video');
function loadVideo(file){if(!file?.type.startsWith('video/'))return toast('Choose a video file');videoUrl=URL.createObjectURL(file);video.src=videoUrl;video.style.display='block';$('#videoDrop').style.display='none';videoReady=true;video.onloadedmetadata=()=>{$('#duration').textContent=fmt(video.duration);$('#endTime').value=video.duration.toFixed(1);$('#scrubber').max=video.duration;$('#endTime').max=video.duration;toast('Video loaded')}}
$('#chooseVideo').onclick=$('#videoUploadBtn').onclick=()=>$('#videoInput').click();$('#videoInput').onchange=e=>loadVideo(e.target.files[0]);
$('#playBtn').onclick=()=>{if(!videoReady)return toast('Add a video first');video.paused?video.play():video.pause();};video.ontimeupdate=()=>{$('#currentTime').textContent=fmt(video.currentTime);$('#scrubber').value=video.currentTime;if(+$('#endTime').value&&video.currentTime>=+$('#endTime').value)video.pause()};$('#scrubber').oninput=e=>video.currentTime=+e.target.value;
$('#startTime').onchange=e=>{if(videoReady)video.currentTime=Math.max(0,Math.min(+e.target.value,video.duration))};$('#endTime').onchange=e=>{if(videoReady)e.target.value=Math.min(video.duration,Math.max(+$('#startTime').value+.1,+e.target.value))};
function fmt(s){s=Math.max(0,s||0);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(Math.floor(s%60)).padStart(2,'0')}
const vtools={trim:()=>'<p class="hint">Set the start and end points below, then preview your selection.</p>',speed:()=>'<div class="control"><label>Playback speed <output id="speedOut">1×</output></label><input id="speed" type="range" min=".25" max="2" step=".25" value="1"></div><p class="hint">Speed changes apply to preview. Export records the selected clip at the chosen speed.</p>',filter:()=>'<div class="filter-grid">'+[['none','Original'],['grayscale(1)','B&W'],['sepia(1)','Vintage'],['contrast(1.25) saturate(.7)','Film'],['saturate(1.7)','Pop'],['hue-rotate(25deg)','Dream']].map(x=>'<button class="choice" data-vfilter="'+x[0]+'">'+x[1]+'</button>').join('')+'</div>',text:()=>'<div class="control"><label>Video title</label><input class="text-input" id="videoOverlayInput" maxlength="36" placeholder="Your words..."></div>',audio:()=>'<p class="hint">Add your own soundtrack locally. Browser export support for audio tracks varies by device.</p><input id="audioInput" type="file" accept="audio/*">'};
function vpanelTool(name){$('#vtoolTitle').textContent=name[0].toUpperCase()+name.slice(1);$('#vtoolContent').innerHTML=vtools[name]();if(name==='speed')$('#speed').oninput=e=>{video.playbackRate=+e.target.value;$('#speedOut').textContent=e.target.value+'×'};if(name==='text')$('#videoOverlayInput').oninput=e=>$('#videoText').textContent=e.target.value;if(name==='filter')$$('[data-vfilter]').forEach(b=>b.onclick=()=>{video.style.filter=b.dataset.vfilter})}
$$('.tool').filter(b=>b.dataset.vtool).forEach(b=>b.onclick=()=>{$$('.tool').filter(x=>x.dataset.vtool).forEach(x=>x.classList.remove('active'));b.classList.add('active');vpanelTool(b.dataset.vtool)});vpanelTool('trim');
$('#exportVideo').onclick=async()=>{if(!videoReady)return toast('Add a video first');const start=+$('#startTime').value,end=+$('#endTime').value||video.duration;if(end<=start)return toast('End time must be after start');video.currentTime=start;const stream=video.captureStream?.();if(!stream||!MediaRecorder)return toast('Video export is not supported by this browser');const chunks=[];const rec=new MediaRecorder(stream,{mimeType:'video/webm'});rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{const blob=new Blob(chunks,{type:'video/webm'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nexa-studio-clip.webm';a.click();toast('Video exported')};video.muted=false;rec.start();video.play();const stop=()=>{if(video.currentTime>=end){video.pause();rec.stop();video.removeEventListener('timeupdate',stop)}};video.addEventListener('timeupdate',stop);};

let cameraStream=null,cameraFacing='environment',recording=null,recordChunks=[];const cameraModal=$('#cameraModal'),cameraPreview=$('#cameraPreview');async function openCamera(){cameraModal.classList.remove('hidden');$('#cameraStatus').textContent='Requesting camera…';try{await startCamera()}catch(e){$('#cameraStatus').textContent='Camera permission unavailable.';toast('Camera could not be opened')}}async function startCamera(){if(cameraStream)cameraStream.getTracks().forEach(t=>t.stop());cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:cameraFacing,width:{ideal:1920},height:{ideal:1080}},audio:true});cameraPreview.srcObject=cameraStream;$('#cameraStatus').textContent=cameraFacing==='environment'?'Rear camera':'Front camera'}function closeCamera(){if(recording)stopRecording();if(cameraStream)cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null;cameraPreview.srcObject=null;cameraModal.classList.add('hidden')}$('#captureLaunch').onclick=openCamera;$('#closeCamera').onclick=closeCamera;$('#cameraFlip').onclick=async()=>{cameraFacing=cameraFacing==='environment'?'user':'environment';try{await startCamera()}catch(e){toast('Camera switch unavailable')}};$('#cameraShutter').onclick=()=>{if(!cameraStream)return;const c=document.createElement('canvas');c.width=cameraPreview.videoWidth;c.height=cameraPreview.videoHeight;c.getContext('2d').drawImage(cameraPreview,0,0,c.width,c.height);c.toBlob(blob=>{if(blob){loadPhoto(new File([blob],'nexa-capture.jpg',{type:'image/jpeg'}));closeCamera();showMode('photo');toast('Captured — ready to edit')}},'image/jpeg',.94)};$('#cameraRecord').onclick=()=>{if(recording){stopRecording();return}if(!window.MediaRecorder||!cameraStream)return toast('Video recording is not supported here');recordChunks=[];recording=new MediaRecorder(cameraStream,{mimeType:'video/webm'});recording.ondataavailable=e=>e.data.size&&recordChunks.push(e.data);recording.onstop=()=>{const blob=new Blob(recordChunks,{type:'video/webm'});loadVideo(new File([blob],'nexa-capture.webm',{type:'video/webm'}));closeCamera();showMode('video');toast('Video captured — ready to edit');recording=null;$('#cameraRecord').textContent='●'};recording.start();$('#cameraRecord').textContent='■';$('#cameraStatus').textContent='Recording…'};function stopRecording(){if(recording&&recording.state!=='inactive')recording.stop()}