const authorStore={
  get(){try{return JSON.parse(localStorage.getItem('novella-author-profile')||'null')}catch{return null}},
  save(p){localStorage.setItem('novella-author-profile',JSON.stringify(p))},
  books(){try{return JSON.parse(localStorage.getItem('novella-author-books')||'[]')}catch{return []}},
  saveBooks(b){localStorage.setItem('novella-author-books',JSON.stringify(b))}
};
const authorEsc=s=>esc(String(s||''));
function authorBooks(){return authorStore.books()}
function authorBookText(book){return book.chapters.map((c,i)=>`Chapter ${i+1}\n\n${c.text}`).join('\n\n')}
function authorUrl(book){return 'data:text/plain;charset=utf-8,'+encodeURIComponent(authorBookText(book))}
function localBooks(){return authorBooks().filter(b=>b.published).map(b=>({id:'author-'+b.id,title:b.title,author:b.author,genre:b.genre||'Contemporary',year:new Date(b.publishedAt||Date.now()).getFullYear(),description:b.description||'A story published by a Novella author.',url:authorUrl(b),cover:b.cover||'linear-gradient(145deg,#312e81,#c084fc)',local:true}))}
function studio(){
  const p=authorStore.get()||{name:'',bio:''};
  const books=authorBooks();
  $('#studioContent').innerHTML=`<div class="studio-head"><div><div class="eyebrow">Creator space</div><h2>Author Studio</h2><p class="muted">Write, edit and publish your stories on this device.</p></div><button class="secondary" id="studioClose">Close</button></div>
  <div class="studio-tabs"><button class="chip active" data-stab="dashboard">Dashboard</button><button class="chip" data-stab="write">Write a novel</button></div>
  <section id="studioDashboard" class="studio-panel"><div class="studio-profile"><div class="avatar">${initials(p.name||'A')}</div><div><strong>${authorEsc(p.name||'New author')}</strong><p class="muted">${authorEsc(p.bio||'Add an author bio to introduce yourself.')}</p></div><button class="secondary" id="editAuthor">Edit profile</button></div><div class="studio-stats"><div><strong>${books.length}</strong><span>Stories</span></div><div><strong>${books.filter(b=>b.published).length}</strong><span>Published</span></div><div><strong>${books.filter(b=>!b.published).length}</strong><span>Drafts</span></div></div><div class="studio-list"><div class="section-head"><h3>My stories</h3><button class="primary" id="newStory">+ New story</button></div>${books.length?books.map(authorRow).join(''):'<div class="empty"><h3>Your writing starts here</h3><p class="muted">Create your first novel and add chapters.</p></div>'}</div></section>
  <section id="studioWrite" class="studio-panel hidden"><form id="storyForm" class="story-form"><input type="hidden" id="storyId"><label>Author name<input id="storyAuthor" maxlength="60" value="${authorEsc(p.name)}" placeholder="Your author name" required></label><label>Title<input id="storyTitle" maxlength="100" placeholder="Novel title" required></label><label>Genre<select id="storyGenre"><option>Romance</option><option>Fantasy</option><option>Mystery</option><option>Adventure</option><option>Horror</option><option>Science Fiction</option><option>Contemporary</option><option>Young Adult</option></select></label><label>Description<textarea id="storyDescription" maxlength="500" placeholder="What is this story about?"></textarea></label><div id="chapterEditor"></div><button type="button" class="secondary" id="addChapter">+ Add chapter</button><div class="story-actions"><button type="button" class="secondary" id="cancelStory">Cancel</button><button type="submit" class="primary">Save draft</button></div></form></section>`;
  $('#studio').classList.remove('hidden');
  $('#studioClose').onclick=closeStudio; $('#editAuthor').onclick=authorProfileForm; $('#newStory').onclick=()=>newStory();
  document.querySelectorAll('[data-stab]').forEach(x=>x.onclick=()=>studioTab(x.dataset.stab));
  $('#addChapter').onclick=()=>addChapterEditor(); $('#cancelStory').onclick=()=>studioTab('dashboard'); $('#storyForm').onsubmit=saveStory;
}
function authorRow(b){return `<div class="story-row"><div class="story-cover" style="background:${authorEsc(b.cover||'linear-gradient(145deg,#312e81,#c084fc)')}">${authorEsc((b.title||'N').slice(0,1))}</div><div class="story-row-main"><strong>${authorEsc(b.title)}</strong><span>${authorEsc(b.genre)} · ${b.chapters?.length||0} chapters</span><small class="${b.published?'published':'draft'}">${b.published?'Published':'Draft'}</small></div><div class="story-row-actions"><button class="secondary" data-edit="${authorEsc(b.id)}">Edit</button>${b.published?`<button class="secondary" data-unpublish="${authorEsc(b.id)}">Unpublish</button>`:`<button class="primary" data-publish="${authorEsc(b.id)}">Publish</button>`}</div></div>`}
function bindStoryRows(){document.querySelectorAll('[data-edit]').forEach(x=>x.onclick=()=>editStory(x.dataset.edit));document.querySelectorAll('[data-publish]').forEach(x=>x.onclick=()=>publishStory(x.dataset.publish));document.querySelectorAll('[data-unpublish]').forEach(x=>x.onclick=()=>unpublishStory(x.dataset.unpublish))}
function studioTab(tab){$('#studioDashboard').classList.toggle('hidden',tab!=='dashboard');$('#studioWrite').classList.toggle('hidden',tab!=='write');document.querySelectorAll('[data-stab]').forEach(x=>x.classList.toggle('active',x.dataset.stab===tab));if(tab==='dashboard'){studio();bindStoryRows()}}
function authorProfileForm(){
 const p=authorStore.get()||{name:'',bio:''};
 $('#studioContent').innerHTML=`<div class="studio-head"><div><div class="eyebrow">Author identity</div><h2>Your author profile</h2></div><button class="secondary" id="backStudio">Back</button></div><form id="authorForm" class="story-form"><label>Author name<input id="authorName" maxlength="60" value="${authorEsc(p.name)}" required placeholder="Pen name or real name"></label><label>Bio<textarea id="authorBio" maxlength="240" placeholder="Tell readers about yourself">${authorEsc(p.bio)}</textarea></label><button class="primary">Save author profile</button></form>`;
 $('#backStudio').onclick=studio; $('#authorForm').onsubmit=e=>{e.preventDefault();authorStore.save({name:$('#authorName').value.trim(),bio:$('#authorBio').value.trim(),updated:Date.now()});studio();};
}
function newStory(){
 studioTab('write'); $('#storyId').value='';$('#storyAuthor').value=authorStore.get()?.name||'';$('#storyTitle').value='';$('#storyDescription').value='';$('#storyGenre').value='Contemporary';$('#chapterEditor').innerHTML='';addChapterEditor();
}
function addChapterEditor(title='',text=''){const n=document.querySelectorAll('.chapter-editor').length+1;const el=document.createElement('div');el.className='chapter-editor';el.innerHTML=`<div class="chapter-editor-head"><strong>Chapter ${n}</strong><button type="button" class="iconbtn remove-chapter">×</button></div><input class="chapter-title" maxlength="100" value="${authorEsc(title)}" placeholder="Chapter title"><textarea class="chapter-text" placeholder="Write your chapter here…" required>${authorEsc(text)}</textarea>`;$('#chapterEditor').appendChild(el);el.querySelector('.remove-chapter').onclick=()=>{if(document.querySelectorAll('.chapter-editor').length>1){el.remove();renumberChapters()}}}
function renumberChapters(){document.querySelectorAll('.chapter-editor').forEach((x,i)=>x.querySelector('strong').textContent=`Chapter ${i+1}`)}
function saveStory(e){e.preventDefault();const id=$('#storyId').value||String(Date.now());const chapters=[...document.querySelectorAll('.chapter-editor')].map(x=>({title:x.querySelector('.chapter-title').value.trim(),text:x.querySelector('.chapter-text').value.trim()})).filter(x=>x.text);if(!chapters.length){alert('Add at least one chapter.');return}const books=authorBooks();const old=books.find(b=>b.id===id);const b={id,author:$('#storyAuthor').value.trim(),title:$('#storyTitle').value.trim(),genre:$('#storyGenre').value,description:$('#storyDescription').value.trim(),chapters,published:old?.published||false,createdAt:old?.createdAt||Date.now(),publishedAt:old?.publishedAt||null,cover:old?.cover||'linear-gradient(145deg,#312e81,#c084fc)'};const idx=books.findIndex(x=>x.id===id);if(idx>=0)books[idx]=b;else books.unshift(b);authorStore.saveBooks(books);studio();bindStoryRows()}
function editStory(id){const b=authorBooks().find(x=>x.id===id);if(!b)return;studioTab('write');$('#storyId').value=b.id;$('#storyAuthor').value=b.author;$('#storyTitle').value=b.title;$('#storyGenre').value=b.genre;$('#storyDescription').value=b.description||'';$('#chapterEditor').innerHTML='';b.chapters.forEach(c=>addChapterEditor(c.title,c.text))}
function publishStory(id){const books=authorBooks();const b=books.find(x=>x.id===id);if(!b)return;b.published=true;b.publishedAt=Date.now();authorStore.saveBooks(books);studio();bindStoryRows();render()}
function unpublishStory(id){const books=authorBooks();const b=books.find(x=>x.id===id);if(!b)return;b.published=false;authorStore.saveBooks(books);studio();bindStoryRows();render()}
function closeStudio(){$('#studio').classList.add('hidden')}
function injectPublished(){const app=$('#app');if(!app||location.hash&&location.hash!=='#home'&&location.hash!=='')return;const pubs=localBooks();if(!pubs.length)return;let sec=app.querySelector('[data-local-published]');if(!sec){sec=document.createElement('section');sec.className='section';sec.dataset.localPublished='1';sec.innerHTML='<div class="section-head"><h2>From Novella authors</h2><span class="muted">Community stories</span></div><div class="grid"></div>';app.appendChild(sec)}const grid=sec.querySelector('.grid');grid.innerHTML=pubs.map(b=>`<article class="book" onclick="openBook('${authorEsc(b.id)}')"><div class="cover" style="background:${b.cover}"><span>${authorEsc(b.title)}</span></div><div class="book-info"><div class="book-title">${authorEsc(b.title)}</div><div class="book-author">${authorEsc(b.author)}</div><div class="book-meta">${authorEsc(b.genre)} · ${b.chapters.length} chapters</div></div></article>`).join('')}
const originalOpenBook=window.openBook;window.openBook=function(id){if(String(id).startsWith('author-')){const b=localBooks().find(x=>x.id===id);if(!b)return;state.book=b;state.chapter=0;state.loaded=false;$('#readerTitle').textContent=b.title;$('#readerChapter').textContent=b.author;$('#bookmarkBtn').textContent=saved().includes(id)?'♥':'♡';$('#reader').classList.remove('hidden');loadText(b);return}return originalOpenBook(id)};
const originalRender=window.render;window.render=function(){originalRender();setTimeout(injectPublished,0)};
document.addEventListener('DOMContentLoaded',()=>{$('#studioBtn')?.addEventListener('click',studio);$('#closeStudio')?.addEventListener('click',closeStudio);$('#studio')?.addEventListener('click',e=>{if(e.target.id==='studio')closeStudio()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeStudio()});setTimeout(injectPublished,50);});