/* Goalora Smart Goal Planner: category templates + automatic quantity progress + quick updates. */
(function(){
  const TEMPLATES={
    'Clothes':{items:['Trousers','Shirts','T-shirts','Jeans','Shorts','Dresses','Skirts','Jackets','Sweaters','Hoodies','Suits','Shoes','Sandals','Bags','Belts','Underwear','Socks','Caps','Other'],examples:['Build my wardrobe','Buy 5 trousers','Complete my wardrobe']},
    'House':{items:['Bed','Mattress','Sofa','Dining table','Chairs','Wardrobe','Curtains','Carpet','TV','Fridge','Cooker','Microwave','Kitchen utensils','Bedding','Bathroom items','Decorations','Other'],examples:['Furnish my bedroom','Buy 4 chairs','Set up my house']},
    'Education':{items:['Books','Course','Unit','Exam','Assignment','Certificate','Skill','Training','Revision sessions','School fees','Other'],examples:['Read 5 books','Complete a course','Finish my semester']},
    'Finance':{items:['Savings','Emergency fund','Investment','Debt repayment','Rent','School fees','Business capital','Phone','Car','Land','House','Other'],examples:['Save KSh 100,000','Build an emergency fund','Pay off debt']},
    'Health & Fitness':{items:['Gym sessions','Runs','Walks','Workouts','Meals','Water days','Medical checkup','Dental visit','Sleep days','Weight milestone','Other'],examples:['Complete 20 workouts','Run 50 km','Drink enough water for 30 days']},
    'Travel':{items:['Destination','Trip','Flight','Bus ticket','Hotel night','Activity','Passport task','Visa task','Travel fund','Other'],examples:['Visit 3 destinations','Plan a holiday','Save for a trip']},
    'Personal Growth':{items:['Book','Course','Skill','Habit','Journal days','Meditation days','Project','Challenge','Other'],examples:['Read 10 books','Learn a new skill','Complete a 30-day challenge']},
    'Relationships':{items:['Date','Family visit','Call','Gift','Quality-time day','Trip','Activity','Milestone','Other'],examples:['Plan 5 dates','Visit family 4 times','Create more quality time']},
    'Business':{items:['Customer','Product','Sale','Order','Client','Lead','Campaign','Project','Employee','Business task','Other'],examples:['Get 20 customers','Make 50 sales','Launch a product']},
    'Fun & Hobbies':{items:['Book','Movie','Game','Workout','Drawing','Song','Project','Event','Trip','Other'],examples:['Read 5 novels','Finish 3 art projects','Play 10 games']},
    'Spirituality':{items:['Prayer day','Reading day','Service','Study session','Meditation','Fellowship','Reflection day','Other'],examples:['Complete 30 days of prayer','Read a book','Attend 10 services']},
    'Lifestyle':{items:['Morning routine','Declutter task','Cooking day','Self-care day','Digital detox day','Home task','Personal task','Other'],examples:['Complete a 30-day routine','Declutter my room','Build a better routine']}
  };
  const FALLBACK={items:['Task','Item','Session','Step','Milestone','Other'],examples:['Complete 5 tasks','Finish my project','Reach my target']};
  const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
  const tpl=c=>TEMPLATES[c]||FALLBACK;
  const data=()=>window.goaloraData?.get?.();
  function css(){if(document.getElementById('smartGoalStyle'))return;const s=document.createElement('style');s.id='smartGoalStyle';s.textContent=`.smart-goal-box{grid-column:1/-1;padding:15px 16px;border:1px solid var(--line);border-radius:15px;background:linear-gradient(145deg,rgba(99,91,255,.07),rgba(35,184,231,.04))}.smart-goal-title{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.smart-goal-title strong{font-size:13px}.smart-auto{font-size:9px;font-weight:850;padding:5px 8px;border-radius:99px;background:rgba(29,187,131,.11);color:var(--success)}.smart-goal-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px}.smart-goal-grid label{font-size:10px}.smart-goal-grid input,.smart-goal-grid select{margin-top:6px;width:100%}.smart-progress-message{margin-top:10px;color:var(--muted);font-size:10px;line-height:1.45}.smart-examples{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.smart-example{background:var(--surface);border:1px solid var(--line);color:var(--muted);padding:6px 8px;border-radius:9px;font-size:9px;cursor:pointer}.smart-example:hover{color:var(--primary);border-color:var(--primary)}.quantity-update{margin:15px 0;padding:15px;border:1px solid var(--line);border-radius:15px;background:var(--surface-2)}.quantity-update h3{margin:0 0 5px;font-size:13px}.quantity-update p{margin:0 0 10px;color:var(--muted);font-size:10px}.quantity-controls{display:flex;gap:8px;align-items:center}.quantity-controls input{width:110px;background:var(--surface);border:1px solid var(--line);border-radius:10px;padding:9px;color:var(--text)}.quantity-result{margin-top:9px;font-size:11px;font-weight:750;color:var(--primary)}@media(max-width:700px){.smart-goal-grid{grid-template-columns:1fr 1fr}}@media(max-width:480px){.smart-goal-grid{grid-template-columns:1fr}.quantity-controls{flex-wrap:wrap}}`;document.head.appendChild(s)}
  function getForm(){return document.getElementById('goalForm')}
  function getGoal(id){return data()?.goals?.find(g=>g.id===id)}
  function smartBox(existing){const f=getForm();if(!f)return;let box=document.getElementById('smartGoalBox');if(!box){box=document.createElement('div');box.id='smartGoalBox';box.className='smart-goal-box';f.insertBefore(box,f.querySelector('.form-actions')||null)}const t=tpl(f.elements.category.value);box.innerHTML=`<div class="smart-goal-title"><strong>Smart progress</strong><span class="smart-auto">AUTOMATIC %</span></div><div class="smart-goal-grid"><label>What are you tracking?<select id="smartItem">${t.items.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select></label><label>Target quantity<input id="smartTarget" type="number" min="1" step="1" placeholder="e.g. 5"></label><label>Completed so far<input id="smartCompleted" type="number" min="0" step="1" value="0" placeholder="e.g. 1"></label></div><div class="smart-progress-message" id="smartMessage"></div><div class="smart-examples">${t.examples.map(x=>`<button type="button" class="smart-example" data-example="${esc(x)}">${esc(x)}</button>`).join('')}</div>`;const item=document.getElementById('smartItem'),target=document.getElementById('smartTarget'),done=document.getElementById('smartCompleted');if(existing?.goalItem&&[...item.options].some(o=>o.value===existing.goalItem))item.value=existing.goalItem;target.value=existing?.targetQty??'';done.value=existing?.completedQty??0;const update=()=>{let a=Math.max(0,Number(target.value||0)),b=Math.max(0,Number(done.value||0));if(a)b=Math.min(b,a);const p=a?Math.round(b/a*100):0;const slider=document.getElementById('goalProgress'),pv=document.getElementById('progressValue');if(slider)slider.value=p;if(pv)pv.textContent=p+'%';const msg=document.getElementById('smartMessage');if(msg)msg.textContent=a?`${b} of ${a} ${item.value.toLowerCase()} completed → ${p}% automatically.`:'Set a target quantity. Then update the completed quantity as you make progress.'};target.addEventListener('input',update);done.addEventListener('input',update);item.addEventListener('change',update);box.querySelectorAll('[data-example]').forEach(b=>b.addEventListener('click',()=>{f.elements.name.value=b.dataset.example;const m=b.dataset.example.match(/\b(\d+)\b/);if(m)target.value=m[1];update()}));update()}
  function categoryOptions(){const f=getForm();if(!f)return;const sub=f.elements.subcategory;if(!sub)return;const old=sub.value,t=tpl(f.elements.category.value);sub.innerHTML=`<option value="">Choose an item / area</option>${t.items.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}<option value="Custom">Custom</option>`;if(old&&[...sub.options].some(o=>o.value===old))sub.value=old}
  function updateStoredGoal(name,target,completed,item){const d=data();if(!d?.goals)return;const g=d.goals.find(x=>x.name===name);if(!g)return;const p=target?Math.min(100,Math.round(Math.min(completed,target)/target*100)):0;g.targetQty=target;g.completedQty=target?Math.min(completed,target):completed;g.goalItem=item;g.progress=p;g.status=p>=100?'Completed':p>0?'In Progress':'Not Started';window.goaloraData.save?.()}
  function addQuantityUpdater(){const modal=document.getElementById('detailModal');if(!modal||modal.dataset.quantityReady==='1')return;const h=modal.querySelector('h2');if(!h)return;const name=h.textContent;const g=data()?.goals?.find(x=>x.name===name);if(!g||!g.targetQty)return;modal.dataset.quantityReady='1';const wrap=document.createElement('div');wrap.className='quantity-update';wrap.innerHTML=`<h3>Update your real progress</h3><p>Got another ${esc(g.goalItem||'item')}? Increase the number below. Goalora will calculate the percentage automatically.</p><div class="quantity-controls"><input id="detailCompletedQty" type="number" min="0" max="${g.targetQty}" value="${g.completedQty||0}"><button class="primary" id="saveQuantity">Update progress</button></div><div class="quantity-result">${g.completedQty||0} of ${g.targetQty} completed · ${g.progress||0}%</div>`;const body=modal.querySelector('.detail-body');if(body)body.insertBefore(wrap,body.firstChild);document.getElementById('saveQuantity').addEventListener('click',()=>{const n=Math.max(0,Math.min(g.targetQty,Number(document.getElementById('detailCompletedQty').value||0)));g.completedQty=n;g.progress=Math.round(n/g.targetQty*100);g.status=g.progress>=100?'Completed':g.progress>0?'In Progress':'Not Started';window.goaloraData.save?.();if(window.render)window.render();if(window.openDetail)window.openDetail(g.id);else toast?.('Progress updated')})}
  function install(){const f=getForm();if(!f||f.dataset.smartInstalled)return;f.dataset.smartInstalled='1';f.elements.category?.addEventListener('change',()=>{categoryOptions();smartBox(null)});document.addEventListener('click',e=>{const edit=e.target.closest?.('[data-edit]'),newBtn=e.target.closest?.('#headNewGoal,#sidebarNewGoal');if(edit)setTimeout(()=>{categoryOptions();smartBox(getGoal(edit.dataset.edit))},30);else if(newBtn)setTimeout(()=>{categoryOptions();smartBox(null)},30)});document.addEventListener('submit',e=>{if(e.target!==f)return;const target=Number(document.getElementById('smartTarget')?.value||0),completed=Number(document.getElementById('smartCompleted')?.value||0),item=document.getElementById('smartItem')?.value||'',name=f.elements.name.value,p=target?Math.min(100,Math.round(Math.min(completed,target)/target*100)):0;f.elements.progress.value=p;f.elements.status.value=p>=100?'Completed':p>0?'In Progress':'Not Started';setTimeout(()=>{updateStoredGoal(name,target,completed,item);window.render?.()},100)},true)}
  css();const observer=new MutationObserver(()=>{if(getForm())install();addQuantityUpdater()});observer.observe(document.body,{childList:true,subtree:true});window.addEventListener('load',()=>setTimeout(()=>{install();categoryOptions()},150));
})();
