const $=id=>document.getElementById(id);const scene=$('scene'),opening=$('opening'),dialogue=$('dialogue'),speaker=$('speaker'),text=$('dialogueText'),choices=$('choices'),progress=$('progressBar'),chapter=$('chapter'),flash=$('flash'),toast=$('toast'),phone=$('phoneGlow');let step=0,paused=false,story=[];
const scenes={
start:{chapter:'CHAPTER 01 · 2:13 AM',env:'street',camera:'wide',speaker:'NARRATOR',text:'2:13 AM. Jay is three streets from home. The city is almost empty. A message arrives.',next:'message'},
message:{chapter:'CHAPTER 01 · THE MESSAGE',env:'street',camera:'close',speaker:'PHONE',text:'UNKNOWN: “DON’T GO HOME. THEY ARE WAITING FOR YOU.”',choices:[['Ignore it.','ignore'],['Read the full message.','read']]},
ignore:{chapter:'CHAPTER 02 · THE STREET',env:'street',camera:'chase',speaker:'JAY',text:'“It is probably a prank.” Jay keeps walking. A black car turns the corner and slows behind him.',choices:[['Run.','run'],['Go home anyway.','home']]},
read:{chapter:'CHAPTER 02 · THE PIN',env:'street',camera:'push',speaker:'PHONE',text:'“You have seven minutes. Find the blue door. Bring nobody. Trust nobody.” A location pin appears.',choices:[['Follow the pin.','follow'],['Call the number.','call']]},
home:{chapter:'CHAPTER 03 · HOME',env:'house',camera:'slow',speaker:'NARRATOR',text:'Jay reaches his house. The front door is open. He knows he locked it.',choices:[['Go inside.','inside'],['Walk away.','run']]},
inside:{chapter:'CHAPTER 03 · THE HOUSE',env:'house',camera:'close',speaker:'JAY',text:'The lights are off. A photograph on the table shows Jay standing outside an abandoned cinema — tomorrow.',choices:[['Take the photograph.','follow'],['Leave the house.','run']]},
run:{chapter:'CHAPTER 03 · THE CHASE',env:'chase',camera:'shake',speaker:'NARRATOR',text:'Jay runs. Footsteps follow. The car accelerates. Rain begins. Ahead, a blue door glows beneath a broken streetlight.',choices:[['Enter the blue door.','door'],['Hide behind the car.','hide']]},
follow:{chapter:'CHAPTER 03 · THE CINEMA',env:'cinema',camera:'travel',speaker:'JAY',text:'The pin leads Jay to the abandoned Orpheum Cinema. Its sign flickers in the rain. One blue door is unlocked.',choices:[['Open the blue door.','door'],['Leave.','leave']]},
call:{chapter:'CHAPTER 03 · THE CALL',env:'street',camera:'close',speaker:'UNKNOWN',text:'The call connects. Silence. Then: “You already know why you were chosen.”',choices:[['Ask who they are.','ask'],['Hang up.','hang']]},
door:{chapter:'CHAPTER 04 · THE CINEMA',env:'cinema',camera:'reveal',speaker:'NARRATOR',text:'The door opens into an old cinema. Every seat is empty. The projector turns on by itself.',choices:[['Watch the screen.','watch'],['Search backstage.','backstage']]},
hide:{chapter:'CHAPTER 04 · THE STRANGER',env:'stranger',camera:'close',speaker:'STRANGER',text:'A hooded stranger steps from the darkness. “If you stay hidden, you survive tonight. If you walk out, you change everything.”',choices:[['Face them.','face'],['Stay hidden.','stay']]},
leave:{chapter:'CHAPTER 04 · THE ESCAPE',env:'street',camera:'pull',speaker:'JAY',text:'Jay walks away. The city becomes strangely quiet. His phone rings one final time.',choices:[['Answer.','answer'],['Keep walking.','walk']]},
ask:{chapter:'CHAPTER 04 · THE TRUTH',env:'cinema',camera:'close',speaker:'UNKNOWN',text:'“Your father left something behind. Something people will kill to possess.” A location arrives: the cinema.',choices:[['Go inside.','door'],['Call the police.','police']]},
hang:{chapter:'CHAPTER 04 · NO SIGNAL',env:'street',camera:'wide',speaker:'NARRATOR',text:'The call ends. Every streetlight around Jay goes dark at once.',choices:[['Keep moving.','walk'],['Call someone you trust.','trust']]},
watch:{chapter:'CHAPTER 05 · TOMORROW',env:'cinema',camera:'push',speaker:'TOMORROW-JAY',text:'On the screen, tomorrow-Jay looks directly at the camera: “Whatever you do next… do not trust the person who brought you here.”',choices:[['Keep watching.','reveal'],['Unplug the projector.','backstage']]},
backstage:{chapter:'CHAPTER 05 · THE BOX',env:'cinema',camera:'reveal',speaker:'NARRATOR',text:'Behind the screen is a hidden room. A small metal box waits under a single light. Jay’s name is engraved on it.',choices:[['Open it.','ending1'],['Leave it.','ending2']]},
face:{chapter:'CHAPTER 05 · THE STRANGER',env:'stranger',camera:'close',speaker:'STRANGER',text:'The hood falls. Jay freezes. It is someone he thought was gone forever.',choices:[['Step closer.','ending3'],['Run.','ending4']]},
stay:{chapter:'CHAPTER 05 · HIDING',env:'cinema',camera:'slow',speaker:'NARRATOR',text:'Jay waits until sunrise. Nobody finds him. On the floor is a photograph dated tomorrow.',choices:[['Pick it up.','ending2'],['Leave it.','ending4']]},
answer:{chapter:'CHAPTER 05 · THE CALL',env:'stranger',camera:'close',speaker:'UNKNOWN',text:'“The blue door was never the danger. The danger is whoever sent you the message.”',choices:[['Ask for the name.','ending3'],['Hang up forever.','ending4']]},
walk:{chapter:'CHAPTER 05 · DAWN',env:'dawn',camera:'pull',speaker:'NARRATOR',text:'Jay keeps walking. Dawn begins to break. For the first time tonight, the city feels safe.',choices:[['Look at the phone.','ending2'],['Keep walking.','ending4']]},
trust:{chapter:'CHAPTER 05 · TRUST',env:'stranger',camera:'close',speaker:'NARRATOR',text:'Jay calls the one person he trusts. They answer immediately: “I have been waiting for your call.”',choices:[['Tell them everything.','ending3'],['Say nothing.','ending4']]},
reveal:{chapter:'FINAL CHAPTER · THE REVEAL',env:'stranger',camera:'orbit',speaker:'TOMORROW-JAY',text:'“If you are watching this, you made it. Now look behind you.” Jay turns.',choices:[['Turn around.','ending1']]},
police:{chapter:'FINAL CHAPTER · THE WARNING',env:'police',camera:'wide',speaker:'NARRATOR',text:'Police lights flood the cinema. But the building is empty. On the wall: “You should have trusted yourself.”',choices:[['Touch the message.','ending1']]},
ending1:{chapter:'ENDING · THE TRUTH',env:'cinema',camera:'pull',speaker:'NARRATOR',text:'The box opens. Inside: a key, a photograph, and one final message — “This is only the beginning.” THE END… FOR NOW.',end:true},
ending2:{chapter:'ENDING · THE QUIET',env:'dawn',camera:'wide',speaker:'NARRATOR',text:'Jay walks into the sunrise. He survived the night. Somewhere, another phone begins to ring.',end:true},
ending3:{chapter:'ENDING · THE REUNION',env:'stranger',camera:'close',speaker:'NARRATOR',text:'The truth finally surfaces. The person behind the message was trying to protect Jay all along. But from what?',end:true},
ending4:{chapter:'ENDING · THE UNKNOWN',env:'street',camera:'pull',speaker:'NARRATOR',text:'Jay leaves the city behind. As the credits begin, his phone receives one last message: “RUN.”',end:true}}
function setScene(s){scene.className='scene scene-'+s.env+' camera-'+(s.camera||'wide');chapter.textContent=s.chapter;progress.style.width=Math.min(100,Math.max(5,(step/24)*100))+'%';phone.style.opacity=(s.env==='street'||s.env==='house')?'1':'0';document.dispatchEvent(new CustomEvent('movieScene',{detail:{env:s.env,camera:s.camera}}));if(s.env==='chase'){scene.classList.add('scene-chase')}if(s.env==='cinema'){scene.classList.add('scene-cinema')}if(s.env==='house'){scene.classList.add('scene-house')}if(s.env==='stranger'){scene.classList.add('scene-stranger')}if(s.env==='police'){scene.classList.add('scene-police')}if(s.env==='dawn'){scene.classList.add('scene-dawn')}}
function show(id){const s=scenes[id];if(!s)return;step++;setScene(s);speaker.textContent=s.speaker;text.textContent=s.text;choices.innerHTML='';dialogue.classList.remove('hidden');if(s.choices)s.choices.forEach(([label,next])=>{const b=document.createElement('button');b.className='choice';b.textContent=label;b.onclick=()=>{story.push(next);flash.style.opacity='.8';setTimeout(()=>flash.style.opacity='0',180);show(next)};choices.appendChild(b)});if(s.end){const b=document.createElement('button');b.className='cinema-btn';b.textContent='↻ PLAY AGAIN';b.onclick=restart;choices.appendChild(b)}toast.textContent=s.end?'THE END':'SCENE CHANGED';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1200)}
function start(){opening.classList.add('hidden');show('start')}function restart(){step=0;story=[];paused=false;$('pause').classList.add('hidden');opening.classList.remove('hidden');dialogue.classList.add('hidden');progress.style.width='0%';scene.className='scene scene-street camera-wide'}
$('startBtn').onclick=start;$('pauseBtn').onclick=()=>{paused=true;$('pause').classList.remove('hidden')};$('resumeBtn').onclick=()=>{paused=false;$('pause').classList.add('hidden')};$('restartBtn').onclick=restart;$('soundBtn').onclick=()=>document.dispatchEvent(new Event('toggleSound'));window.addEventListener('keydown',e=>{if(e.key==='Escape'){$('pause').classList.toggle('hidden');paused=!paused}if(e.key.toLowerCase()==='r')restart()});
