const $=id=>document.getElementById(id);
const scene=$('scene'),opening=$('opening'),dialogue=$('dialogue'),speaker=$('speaker'),text=$('dialogueText'),choices=$('choices'),continueBtn=$('continueBtn'),progress=$('progressBar'),chapter=$('chapter'),flash=$('flash'),toast=$('toast'),phone=$('phoneGlow');
let step=0,paused=false,sound=true,story=[];
const scenes={
start:{chapter:'CHAPTER 01 · THE MESSAGE',scene:'scene-1',camera:'wide',speaker:'NARRATOR',text:'It is 2:13 AM. The city is asleep. Jay is walking home when his phone vibrates once.',next:'message'},
message:{chapter:'CHAPTER 01 · THE MESSAGE',scene:'scene-1',camera:'push',speaker:'PHONE',text:'UNKNOWN NUMBER: “DON’T GO HOME. THEY ARE WAITING FOR YOU.”',choices:[['Ignore it and keep walking.','ignore'],['Stop and read the full message.','read']]},
ignore:{chapter:'CHAPTER 02 · THE WRONG TURN',scene:'scene-2',camera:'chase',speaker:'JAY',text:'“Probably a prank.” Jay puts the phone away. Ten seconds later, a black car turns onto the empty road behind him.',choices:[['Run toward the main road.','run'],['Turn into the dark alley.','alley']]},
read:{chapter:'CHAPTER 02 · THE MESSAGE',scene:'scene-2',camera:'push',speaker:'PHONE',text:'“You have 7 minutes. Find the blue door. Bring nobody. Trust nobody.” A location pin appears.',choices:[['Follow the location.','follow'],['Call the number back.','call']]},
run:{chapter:'CHAPTER 03 · THE CHASE',scene:'scene-3',camera:'shake',speaker:'NARRATOR',text:'Jay runs. Footsteps follow. The car accelerates. Ahead, a blue door glows beneath a broken streetlight.',choices:[['Enter the blue door.','door'],['Hide behind the parked car.','hide']]},
alley:{chapter:'CHAPTER 03 · THE ALLEY',scene:'scene-3',camera:'slow',speaker:'NARRATOR',text:'The alley is silent. Too silent. At the end, a blue door stands open as if someone knew he was coming.',choices:[['Enter the door.','door'],['Turn back.','turn']]},
follow:{chapter:'CHAPTER 03 · THE BLUE DOOR',scene:'scene-3',camera:'travel',speaker:'JAY',text:'The pin leads him across the city to an abandoned cinema. One blue door is still unlocked.',choices:[['Open the door.','door'],['Leave before it is too late.','leave']]},
call:{chapter:'CHAPTER 03 · THE CALL',scene:'scene-4',camera:'close',speaker:'UNKNOWN',text:'The call connects. Nobody speaks. Then a voice whispers: “You already know why you were chosen.”',choices:[['Ask who they are.','ask'],['Hang up.','hang']]},
door:{chapter:'CHAPTER 04 · THE CINEMA',scene:'scene-4',camera:'reveal',speaker:'NARRATOR',text:'Inside is an old cinema. Every seat is empty. On the screen is a recording of Jay… from tomorrow.',choices:[['Watch the recording.','watch'],['Destroy the screen.','destroy']]},
hide:{chapter:'CHAPTER 04 · THE STRANGER',scene:'scene-4',camera:'close',speaker:'STRANGER',text:'A stranger steps from the shadows. “If you stay hidden, you survive tonight. If you walk out, you change everything.”',choices:[['Walk out and face them.','face'],['Stay hidden.','stay']]},
turn:{chapter:'CHAPTER 04 · THE RETURN',scene:'scene-4',camera:'orbit',speaker:'NARRATOR',text:'Jay turns back. The street behind him is empty. His phone lights up again: “Wrong choice.”',choices:[['Keep running.','run'],['Go back to the blue door.','door']]},
leave:{chapter:'CHAPTER 04 · THE ESCAPE',scene:'scene-5',camera:'pull',speaker:'JAY',text:'Jay walks away. The city becomes strangely quiet. His phone rings one final time.',choices:[['Answer.','answer'],['Keep walking.','walk']]},
ask:{chapter:'CHAPTER 04 · THE TRUTH',scene:'scene-4',camera:'close',speaker:'UNKNOWN',text:'“Your father left something behind. Something people will kill to possess.” A location arrives: the cinema.',choices:[['Go to the cinema.','door'],['Tell the police.','police']]},
hang:{chapter:'CHAPTER 04 · NO SIGNAL',scene:'scene-5',camera:'wide',speaker:'NARRATOR',text:'The call ends. Every streetlight around Jay goes dark at once.',choices:[['Keep moving.','walk'],['Call someone you trust.','trust']]},
watch:{chapter:'CHAPTER 05 · TOMORROW',scene:'scene-5',camera:'push',speaker:'JAY',text:'On the screen, tomorrow-Jay looks directly into the camera: “Whatever you do next… do not trust the person who brought you here.”',choices:[['Wait for tomorrow-Jay to reveal more.','reveal'],['Unplug the projector.','destroy']]},
destroy:{chapter:'CHAPTER 05 · THE CHOICE',scene:'scene-5',camera:'reveal',speaker:'NARRATOR',text:'The screen goes black. A hidden door opens behind it. Inside is a small box with Jay’s name engraved on the lid.',choices:[['Open the box.','ending1'],['Leave the box untouched.','ending2']]},
face:{chapter:'CHAPTER 05 · THE STRANGER',scene:'scene-5',camera:'close',speaker:'STRANGER',text:'The stranger lowers their hood. Jay freezes. It is someone he thought was gone forever.',choices:[['Step closer.','ending3'],['Run.','ending4']]},
stay:{chapter:'CHAPTER 05 · HIDING',scene:'scene-5',camera:'slow',speaker:'NARRATOR',text:'Jay stays hidden until sunrise. Nobody finds him. But on the floor is a photograph dated tomorrow.',choices:[['Pick up the photograph.','ending2'],['Leave it there.','ending4']]},
answer:{chapter:'CHAPTER 05 · THE CALL',scene:'scene-5',camera:'close',speaker:'UNKNOWN',text:'“You have one chance. The blue door was never the danger. The danger is whoever sent you the message.”',choices:[['Ask for the name.','ending3'],['Hang up forever.','ending4']]},
walk:{chapter:'CHAPTER 05 · DAWN',scene:'scene-5',camera:'pull',speaker:'NARRATOR',text:'Jay keeps walking. Dawn begins to break. For the first time tonight, the city feels safe.',choices:[['Look at the phone.','ending2'],['Keep walking.','ending4']]},
trust:{chapter:'CHAPTER 05 · TRUST',scene:'scene-5',camera:'close',speaker:'NARRATOR',text:'Jay calls the one person he trusts. They answer immediately: “I have been waiting for your call.”',choices:[['Tell them everything.','ending3'],['Say nothing.','ending4']]},
reveal:{chapter:'FINAL CHAPTER · THE REVEAL',scene:'scene-5',camera:'orbit',speaker:'TOMORROW-JAY',text:'“If you are watching this, you made it. Now look behind you.” Jay turns.',choices:[['Turn around.','ending1']]},
police:{chapter:'FINAL CHAPTER · THE WARNING',scene:'scene-5',camera:'wide',speaker:'NARRATOR',text:'The police arrive. But the location is empty. On the cinema wall, one sentence remains: “You should have trusted yourself.”',choices:[['Touch the message.','ending1']]},
ending1:{chapter:'ENDING · THE TRUTH',scene:'scene-5',camera:'pull',speaker:'NARRATOR',text:'The box opens. Inside is a key, a photograph, and one final message: “This is only the beginning.” THE END… FOR NOW.',end:true},
ending2:{chapter:'ENDING · THE QUIET',scene:'scene-5',camera:'wide',speaker:'NARRATOR',text:'Jay walks into the sunrise. He survived the night, but he knows the story is not finished. Somewhere, another phone begins to ring.',end:true},
ending3:{chapter:'ENDING · THE REUNION',scene:'scene-5',camera:'close',speaker:'NARRATOR',text:'The truth finally surfaces. Jay discovers the person behind the message was trying to protect him all along. But from what?',end:true},
ending4:{chapter:'ENDING · THE UNKNOWN',scene:'scene-5',camera:'pull',speaker:'NARRATOR',text:'Jay leaves the city behind. As the credits begin, his phone receives one last message: “RUN.”',end:true}
};
function setScene(s){scene.className='scene '+(s.scene||'scene-1')+' camera-'+(s.camera||'wide');chapter.textContent=s.chapter;progress.style.width=Math.min(100,Math.max(5,(step/20)*100))+'%';phone.style.opacity=s.scene==='scene-1'&&step>0?'1':'0'}
function show(id){const s=scenes[id];if(!s)return;step++;setScene(s);speaker.textContent=s.speaker;text.textContent=s.text;choices.innerHTML='';continueBtn.classList.add('hidden');dialogue.classList.remove('hidden');s.choices?.forEach(([label,next])=>{const b=document.createElement('button');b.className='choice';b.textContent=label;b.onclick=()=>{story.push(next);flash.style.opacity='.8';setTimeout(()=>flash.style.opacity='0',180);show(next)};choices.appendChild(b)});if(s.end){const b=document.createElement('button');b.className='cinema-btn';b.textContent='↻ PLAY AGAIN';b.onclick=restart;choices.appendChild(b)}toast.textContent=s.end?'THE END':'CHOICE RECORDED';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1400)}
function start(){opening.classList.add('hidden');show('start')}
function restart(){step=0;story=[];paused=false;$('pause').classList.add('hidden');opening.classList.remove('hidden');dialogue.classList.add('hidden');progress.style.width='0%';scene.className='scene scene-1'}
$('startBtn').onclick=start;$('pauseBtn').onclick=()=>{paused=true;$('pause').classList.remove('hidden')};$('resumeBtn').onclick=()=>{paused=false;$('pause').classList.add('hidden')};$('restartBtn').onclick=restart;$('soundBtn').onclick=()=>{sound=!sound;$('soundBtn').textContent=sound?'🔊':'🔇';toast.textContent=sound?'SOUND ON':'SOUND OFF';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),900)};
window.addEventListener('keydown',e=>{if(e.key==='Escape'){$('pause').classList.toggle('hidden');paused=!paused}if(e.key.toLowerCase()==='r')restart()});
