const socialStore={
 get(k,f=[]){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}},
 set(k,v){localStorage.setItem(k,JSON.stringify(v))}
};
function socialBookId(){return state.book?.id||''}
function reviewsFor(id){return socialStore.get('novella-reviews-'+id,[])}
function renderReviews(id){const box=$('#socialReviews');if(!box)return;const rs=reviewsFor(id);box.innerHTML=`<div class="social-head"><h3>Reader reviews</h3><span class="muted">${rs.length} review${rs.length===1?'':'s'}</span></div>${rs.length?rs.slice().reverse().map(r=>`<div class="review"><div class="avatar avatar-sm">${authorEsc(initials(r.name||'Reader'))}</div><div><strong>${authorEsc(r.name||'Reader')}</strong><div class="stars">${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}</div><p>${authorEsc(r.text)}</p><small class="muted">${new Date(r.createdAt).toLocaleDateString()}</small></div></div>`).join(''):'<p class="muted">Be the first reader to share your thoughts.</p>'}<form id="reviewForm" class="review-form"><input id="reviewName" maxlength="40" placeholder="Your name" value="${authorEsc(profileStore.get()?.name||'')}"><select id="reviewRating" aria-label="Rating"><option value="5">★★★★★ 5</option><option value="4">★★★★☆ 4</option><option value="3">★★★☆☆ 3</option><option value="2">★★☆☆☆ 2</option><option value="1">★☆☆☆☆ 1</option></select><textarea id="reviewText" maxlength="500" placeholder="Write a review…" required></textarea><button class="primary">Post review</button></form>`;$('#reviewForm').onsubmit=e=>{e.preventDefault();const text=$('#reviewText').value.trim();if(!text)return;const rs=reviewsFor(id);rs.push({name:$('#reviewName').value.trim()||'Reader',rating:Number($('#reviewRating').value),text,createdAt:Date.now()});socialStore.set('novella-reviews-'+id,rs);renderReviews(id)}}
function shareBook(){const b=state.book;if(!b)return;const url=location.href.split('#')[0]+'#book-'+encodeURIComponent(b.id);if(navigator.share)navigator.share({title:b.title,text:`Read ${b.title} on Novella`,url}).catch(()=>{});else navigator.clipboard?.writeText(url).then(()=>alert('Book link copied.'))}
function injectSocial(){if(!$('#detailContent')||!state.book)return;const id=socialBookId();if(!$('#socialReviews')){$('#detailContent').insertAdjacentHTML('beforeend',`<section class="social-section"><div class="social-actions"><button class="secondary" id="shareBook">↗ Share</button><span class="muted">Love this story? Leave a review.</span></div><div id="socialReviews"></div></section>`);$('#shareBook').onclick=shareBook}renderReviews(id)}
const socialOriginalShowDetails=window.showDetails;window.showDetails=function(id){socialOriginalShowDetails(id);setTimeout(injectSocial,0)};
document.addEventListener('DOMContentLoaded',()=>setTimeout(injectSocial,100));